In [1]:
import pandas as pd

In [2]:
df1=pd.DataFrame([['anil',20],['sumil',20]],columns=['name','age'],index=['first','second'])

In [3]:
df1

name  age
first    anil   20
second  sumil   20

In [4]:
data={'name':['anil','sunil','hari'],'age':[10,20,30]}

In [7]:
df2=pd.DataFrame(data,datatype=float,index=[]first',second,'third'],columns=['name','age'])

SyntaxError: invalid syntax (<ipython-input-7-6f3afcbf33f5>, line 1)

In [8]:
df2

NameError: name 'df2' is not defined

In [10]:
data1=[{'a':4,'b':5,'c':2},{'a':1,'b':6,'d':9}]

In [15]:
df3=pd.DataFrame(data1)

data2=[{'a':10,'b':4,'c':1},{'a':5,'b':2,'d':3}]
df4=pd.DataFrame(data2)

df4=df3.append(df4)
df4

a  b    c    d
0   4  5  2.0  NaN
1   1  6  NaN  9.0
0  10  4  1.0  NaN
1   5  2  NaN  3.0

In [16]:
df4.drop(1)

a  b    c   d
0   4  5  2.0 NaN
0  10  4  1.0 NaN

In [17]:
df4

a  b    c    d
0   4  5  2.0  NaN
1   1  6  NaN  9.0
0  10  4  1.0  NaN
1   5  2  NaN  3.0

In [18]:
df4[0:2]

a  b    c    d
0  4  5  2.0  NaN
1  1  6  NaN  9.0

In [19]:
del df4['d']

In [20]:
df4

a  b    c
0   4  5  2.0
1   1  6  NaN
0  10  4  1.0
1   5  2  NaN

In [21]:
df4.pop('c')

0    2.0
1    NaN
0    1.0
1    NaN
Name: c, dtype: float64

In [22]:
df4

a  b
0   4  5
1   1  6
0  10  4
1   5  2

In [23]:
df4['c']=[1,2,3,4]

In [24]:
df4

a  b  c
0   4  5  1
1   1  6  2
0  10  4  3
1   5  2  4

In [25]:
df4['a']

0     4
1     1
0    10
1     5
Name: a, dtype: int64

In [26]:
df4.dtypes

a    int64
b    int64
c    int64
dtype: object

In [27]:
df4.size

12

In [28]:
df4.values

array([[ 4,  5,  1],
       [ 1,  6,  2],
       [10,  4,  3],
       [ 5,  2,  4]], dtype=int64)

In [29]:
df4.axes#

[Int64Index([0, 1, 0, 1], dtype='int64'),
 Index(['a', 'b', 'c'], dtype='object')]

In [30]:
df5=pd.DataFrame({'fruits':['apple','nanana'],'veg':['potato','cauliflower']})
df5

fruits          veg
0   apple       potato
1  nanana  cauliflower

In [31]:
df5.axes

[RangeIndex(start=0, stop=2, step=1), Index(['fruits', 'veg'], dtype='object')]

In [32]:
df5.empty

False

In [33]:
df6=pd.DataFrame([])
df6

Empty DataFrame
Columns: []
Index: []

In [34]:
df6.empty

True

In [35]:
df5.ndim

2

In [45]:
s3=pd.Series([10,20,30,40,50,60,70])
s3

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [37]:
s3.size

4

In [38]:
s3.shape

(4,)

In [39]:
s3.axes

[RangeIndex(start=0, stop=4, step=1)]

In [40]:
s3.ndim

1

In [41]:
s3.dtype

dtype('int64')

In [42]:
s3.values#values return

array([10, 20, 30, 40], dtype=int64)

In [44]:
s3.empty

False

In [47]:
s3.head()

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [48]:
s3.tail()

2    30
3    40
4    50
5    60
6    70
dtype: int64

In [49]:
s3.describe()

count     7.000000
mean     40.000000
std      21.602469
min      10.000000
25%      25.000000
50%      40.000000
75%      55.000000
max      70.000000
dtype: float64

In [50]:
data={'name':['anil','sunil','hari'],'age':[10,20,30],'salary':[20,30,40]}
df=pd.DataFrame(data)
df

age   name  salary
0   10   anil      20
1   20  sunil      30
2   30   hari      40

In [51]:
df.sum()

age                  60
name      anilsunilhari
salary               90
dtype: object

In [52]:
df

age   name  salary
0   10   anil      20
1   20  sunil      30
2   30   hari      40

In [53]:
df.sum(1)#it gives the sum of  row

0    30
1    50
2    70
dtype: int64

In [54]:
df.mean()

age       20.0
salary    30.0
dtype: float64

In [56]:
#count 
df.count()

age       3
name      3
salary    3
dtype: int64

In [57]:
df.min()

age         10
name      anil
salary      20
dtype: object

In [58]:
df.max()

age          30
name      sunil
salary       40
dtype: object

In [60]:
df.prod()

age        6000
salary    24000
dtype: int64

In [61]:
df.cumsum()

age           name salary
0  10           anil     20
1  30      anilsunil     50
2  60  anilsunilhari     90

In [64]:
df.cumprod()


TypeError: can't multiply sequence by non-int of type 'str'

In [65]:
df5=pd.DataFrame({'age':[1,2,3],'salary':[4,5,6]})

In [66]:
df5

age  salary
0    1       4
1    2       5
2    3       6

In [67]:
df5.cumprod()

age  salary
0    1       4
1    2      20
2    6     120

In [71]:
import numpy as np
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [72]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [73]:
df=pd.DataFrame(np.zeros((2,2)))

In [74]:
pd.isnull(df)

0      1
0  False  False
1  False  False

In [77]:
 from numpy import NaN as NA

In [89]:
df=pd.DataFrame([[1,1],[NA,NA]],columns=['first','second'])

In [83]:
pd.notnull(df)

first  second
0   True   False
1  False    True

In [82]:
df.fillna(999)

first  second
0    1.0   999.0
1  999.0     2.0

In [84]:
df.dropna()#for drop any  data

Empty DataFrame
Columns: [first, second]
Index: []

In [85]:
df

first  second
0    1.0     NaN
1    NaN     2.0

In [86]:
df.dropna()

Empty DataFrame
Columns: [first, second]
Index: []

In [87]:
df


first  second
0    1.0     NaN
1    NaN     2.0

In [90]:
df.dropna(how='all',axis=1)

first  second
0    1.0     1.0
1    NaN     NaN